services:
  - type: web
    name: d100
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: ""
      - key: SPRING_DATASOURCE_USERNAME
        value: ""
      - key: SPRING_DATASOURCE_PASSWORD
        value: ""
      - key: SPRING_PROFILES_ACTIVE
        value: "prod"
    healthCheckPath: /api/rules
    autoDeploy: true
