services:
  - type: web
    name: d100
    env: java
    plan: free
    buildCommand: mvn -DskipTests package
    startCommand: java -jar target/d100-0.0.1-SNAPSHOT.jar
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: ""
      - key: SPRING_DATASOURCE_USERNAME
        value: ""
      - key: SPRING_DATASOURCE_PASSWORD
        value: ""
      - key: SPRING_PROFILES_ACTIVE
        value: "prod"
    healthCheckPath: /api/rules
    autoDeploy: true
