services:
  - type: web
    name: d100
    env: docker
    plan: free
    region: frankfurt
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: ""
      - key: SPRING_DATASOURCE_USERNAME
        value: ""
      - key: SPRING_DATASOURCE_PASSWORD
        value: ""
      - key: SPRING_PROFILES_ACTIVE
        value: "prod"
      - key: APP_JWT_SECRET
        value: "aagfewiuighfiehgiehugehrghiehirghherhgegrhehgrehrghehgregergergergeeejrehge7499040444433t4"
    healthCheckPath: /api/rules
    autoDeploy: true
